### ISSUE TITLE
tvbox无法播放阿里云盘的内容，是否是因为阿里云盘封杀了tvbox播放器

### ISSUE THREAD

**Issue by Misakiozo** [cyao2q/files#2]

**Comment by cyao2q** [comment]
并没有 可以自行扫码观看啊 没有开源的token使用了

**Comment by Misakiozo** [comment]
> 并没有 可以自行扫码观看啊 没有开源的token使用了

看不了啊，阿里云扫码了也看不了，加载不出来，我卸载app，换源都不行。不知道怎么办了。手机电视都没法加载出来，不是网盘的资源就可以看，网盘的都看不了，只能用影视app看
