### ISSUE TITLE
电影、电视类型过滤功能无法使用。

### ISSUE THREAD

**Issue by nix2me** [cyao2q/files#5]
版本：TVBox_takagen99_20230616-0831.apk，source-7dd9709都出现过滤功能无法使用。
![Bug图片](https://github.com/cyao2q/files/assets/19586448/812f24c1-a05b-44bf-a04f-bd32973acf89)
测试环境设备：智能电视，华为手机，mumu模拟器。

**Comment by cyao2q** [comment]
哪个资源？

**Comment by cyao2q** [comment]
> 版本：TVBox_takagen99_20230616-0831.apk，source-7dd9709都出现过滤功能无法使用。 ![Bug图片](https://user-images.githubusercontent.com/19586448/249321535-812f24c1-a05b-44bf-a04f-bd32973acf89.png) 测试环境设备：智能电视，华为手机，mumu模拟器。
三三影视的话我这边测试没问题
![image](https://github.com/cyao2q/files/assets/10820724/ccb966b5-f51c-4dc2-9adb-fcc26f48b244)
![image](https://github.com/cyao2q/files/assets/10820724/f548f0e0-9251-4d50-87f1-d564a9b9dd6e)
